# Site metadata
site_name: Adobe Animate Scripting Guide
site_url: https://an-scripting.docsforadobe.dev/
repo_url: https://github.com/docsforadobe/animate-scripting-guide/
repo_name: "animate-scripting-guide"

# Customize navigation
nav:
    - Home: index.md
    - Window:
        - Window object: window/window.md
    - Document:
        - Document object: document/document.md
    - App:
        - Application object: app/app.md


# Do not touch below-- shared for all docs

copyright: All content is copyright Adobe Systems Incorporated.

extra:
    homepage: https://docsforadobe.dev

theme:
    name: material
    custom_dir: overrides
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - search.highlight
        - search.suggest
        - toc.follow
    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: black
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: white
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

extra_css:
    # CSS shared between the whole org
    - https://docsforadobe.dev/_global/global.css
    - https://docsforadobe.dev/_global/global-syntax-highlight.css

    # CSS specific to this file
    - _static/extra.css

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - toc:
        title: Page Contents
        permalink: true
        toc_depth: 3

plugins:
    - git-revision-date-localized
    - search:
        separator: '[\s\-,\.:!=\[\]()"/]+'

    # Note: print-site must be last!
    - print-site:
        add_cover_page: true
        add_print_site_banner: true
        cover_page_template: "overrides/templates/print_site_cover_page.tpl"
        print_page_title: "Offline Docs"
        print_site_banner_template: "overrides/templates/print_site_banner.tpl"
